// rebalancer.rs -- Portfolio rebalancing engine
// Generates minimum-turnover orders to reach target weights with netting,
// minimum trade size enforcement, and turnover budget constraints.

use std::collections::HashMap;

/// Configuration for a rebalancing run.
#[derive(Debug, Clone)]
pub struct RebalanceConfig {
    /// Target portfolio weights keyed by symbol. Must sum to <= 1.0.
    pub target_weights: HashMap<String, f64>,
    /// Current portfolio weights keyed by symbol.
    pub current_weights: HashMap<String, f64>,
    /// Current market prices keyed by symbol (USD per share).
    pub current_prices: HashMap<String, f64>,
    /// Available cash in the portfolio (USD).
    pub cash: f64,
    /// Maximum turnover as a fraction of portfolio value (e.g. 0.20 = 20%).
    pub max_turnover: f64,
    /// Minimum trade size in USD -- orders smaller than this are skipped.
    pub min_trade_size_usd: f64,
    /// Transaction cost in basis points per side.
    pub transaction_cost_bps: f64,
}

/// Side of a rebalancing order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OrderSide {
    Buy,
    Sell,
}

impl std::fmt::Display for OrderSide {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            OrderSide::Buy => write!(f, "BUY"),
            OrderSide::Sell => write!(f, "SELL"),
        }
    }
}

/// A single rebalancing order generated by the engine.
#[derive(Debug, Clone)]
pub struct RebalanceOrder {
    /// Ticker symbol.
    pub symbol: String,
    /// Buy or sell.
    pub side: OrderSide,
    /// Number of shares (fractional shares supported).
    pub shares: f64,
    /// Dollar value of the order.
    pub dollar_value: f64,
    /// Estimated transaction cost in basis points.
    pub estimated_cost_bps: f64,
}

/// Core rebalancing engine.
pub struct Rebalancer;

impl Rebalancer {
    /// Compute the current portfolio value (equity + cash).
    fn portfolio_value(config: &RebalanceConfig) -> f64 {
        let equity: f64 = config
            .current_weights
            .iter()
            .filter_map(|(sym, w)| {
                // weight * portfolio_value -- we need a total, so we solve implicitly:
                // For each symbol: position_usd = weight * total_value
                // total_value = sum(position_usd) + cash
                // total_value = total_value * sum(weights) + cash
                // total_value * (1 - sum(weights)) = cash
                let _ = (sym, w);
                None::<f64>
            })
            .sum();
        let _ = equity;

        // Compute by noting: sum(current_weights) * total_value + cash = total_value
        // => total_value = cash / (1 - sum_weights)  when sum_weights < 1
        // When sum_weights == 1, total_value cannot be determined from weights alone;
        // we use a convention that cash is already reflected in the weights.
        let sum_w: f64 = config.current_weights.values().sum();
        if (sum_w - 1.0).abs() < 1e-9 {
            // Fully invested -- cash is not separately tracked in weights.
            // Fall back: estimate total value from cash as a free float.
            // Caller should provide a portfolio_value separately; we use cash as floor.
            config.cash.max(1.0)
        } else if sum_w < 1.0 {
            config.cash / (1.0 - sum_w)
        } else {
            // Over-invested (sum_w > 1): return cash as fallback to avoid negative values.
            config.cash.max(1.0)
        }
    }

    /// Return total portfolio value assuming current_weights encode fractional allocations
    /// and cash is the residual. When weights sum to 1, the total value must be supplied
    /// separately -- here we approximate it as (sum of position values) inferred from
    /// min_trade_size and cash.
    pub fn total_portfolio_value(config: &RebalanceConfig) -> f64 {
        Self::portfolio_value(config)
    }

    /// Generate rebalancing orders from current to target weights.
    ///
    /// Algorithm:
    /// 1. Compute raw dollar deltas per symbol.
    /// 2. Net buys against sells (reduce gross turnover).
    /// 3. Apply minimum trade size filter.
    /// 4. Apply turnover budget -- prune lowest-priority orders if over budget.
    pub fn compute_orders(config: &RebalanceConfig) -> Vec<RebalanceOrder> {
        let total_value = Self::portfolio_value(config);
        if total_value <= 0.0 {
            return Vec::new();
        }

        // Step 1: compute raw dollar deltas (target_usd - current_usd) per symbol.
        // Collect all unique symbols.
        let mut all_symbols: std::collections::HashSet<String> = std::collections::HashSet::new();
        for k in config.target_weights.keys() {
            all_symbols.insert(k.clone());
        }
        for k in config.current_weights.keys() {
            all_symbols.insert(k.clone());
        }

        // Map symbol -> signed dollar delta (positive = need to buy, negative = need to sell).
        let mut deltas: HashMap<String, f64> = HashMap::new();
        for sym in &all_symbols {
            let target_w = config.target_weights.get(sym).copied().unwrap_or(0.0);
            let current_w = config.current_weights.get(sym).copied().unwrap_or(0.0);
            let delta_usd = (target_w - current_w) * total_value;
            deltas.insert(sym.clone(), delta_usd);
        }

        // Step 2: Netting -- total buys and sells. The net cash flow should balance.
        // In practice the sign of the sum indicates whether we need extra cash (net buy)
        // or will generate cash (net sell). We do not explicitly net across symbols
        // because each symbol has its own delta; the "netting" is implicit in the math.
        // However we apply a netting pass to reduce gross turnover:
        // If a symbol has a small delta that could be offset by the cash freed from sells,
        // we can reduce its order. Here we implement the standard approach:
        // gross_sells = sum of negative deltas (absolute value)
        // gross_buys  = sum of positive deltas
        // net = gross_buys - gross_sells (should be close to 0 if weights are consistent)
        // If net > 0 (more buying than selling), constrain buys proportionally.
        // If net < 0, constrain sells proportionally.

        let gross_sells: f64 = deltas.values().filter(|&&d| d < 0.0).map(|d| d.abs()).sum();
        let gross_buys: f64 = deltas.values().filter(|&&d| d > 0.0).copied().sum();

        // If gross_buys > gross_sells + cash, scale down buys proportionally.
        let available_for_buying = gross_sells + config.cash;
        let buy_scale = if gross_buys > available_for_buying && gross_buys > 0.0 {
            available_for_buying / gross_buys
        } else {
            1.0
        };

        // Similarly if gross_sells > gross_buys + (we need to sell more than we buy),
        // that is fine -- excess cash stays as cash.

        // Apply buy scaling.
        for (sym, delta) in deltas.iter_mut() {
            let _ = sym;
            if *delta > 0.0 {
                *delta *= buy_scale;
            }
        }

        // Step 3: Apply minimum trade size filter.
        let mut filtered: Vec<(String, f64)> = deltas
            .into_iter()
            .filter(|(_, d)| d.abs() >= config.min_trade_size_usd)
            .collect();

        // Sort: sells first (to free cash before buying), then by absolute delta descending.
        filtered.sort_by(|a, b| {
            // Sells (negative) first.
            let a_is_sell = a.1 < 0.0;
            let b_is_sell = b.1 < 0.0;
            if a_is_sell != b_is_sell {
                return b_is_sell.cmp(&a_is_sell); // sells come first
            }
            b.1.abs().partial_cmp(&a.1.abs()).unwrap_or(std::cmp::Ordering::Equal)
        });

        // Step 4: Apply turnover budget.
        // Turnover = (gross_sells + gross_buys) / (2 * total_value) -- one-way convention.
        // Here we use total_sells + total_buys <= max_turnover * total_value.
        let turnover_budget = config.max_turnover * total_value;
        let mut used_turnover = 0.0_f64;
        let mut orders: Vec<RebalanceOrder> = Vec::new();

        for (sym, delta) in filtered {
            let remaining_budget = (turnover_budget - used_turnover).max(0.0);
            if remaining_budget < config.min_trade_size_usd {
                break;
            }

            // Clip to budget.
            let clipped_delta = if delta.abs() > remaining_budget {
                if delta > 0.0 { remaining_budget } else { -remaining_budget }
            } else {
                delta
            };

            // Skip after clipping if below minimum.
            if clipped_delta.abs() < config.min_trade_size_usd {
                continue;
            }

            let price = config.current_prices.get(&sym).copied().unwrap_or(1.0);
            if price <= 0.0 {
                continue;
            }

            let shares = clipped_delta.abs() / price;
            let side = if clipped_delta > 0.0 { OrderSide::Buy } else { OrderSide::Sell };

            orders.push(RebalanceOrder {
                symbol: sym,
                side,
                shares,
                dollar_value: clipped_delta.abs(),
                estimated_cost_bps: config.transaction_cost_bps,
            });

            used_turnover += clipped_delta.abs();
        }

        orders
    }

    /// Estimate the total transaction cost (in USD) for a set of orders.
    pub fn estimate_cost(orders: &[RebalanceOrder], config: &RebalanceConfig) -> f64 {
        let _ = config;
        orders
            .iter()
            .map(|o| o.dollar_value * o.estimated_cost_bps / 10_000.0)
            .sum()
    }

    /// Simulate what the portfolio weights will look like after executing orders.
    ///
    /// Returns a map of symbol -> post-rebalance weight.
    pub fn simulate_post_rebalance_weights(
        orders: &[RebalanceOrder],
        config: &RebalanceConfig,
    ) -> HashMap<String, f64> {
        let total_value = Self::portfolio_value(config);
        if total_value <= 0.0 {
            return config.current_weights.clone();
        }

        // Compute current position values.
        let mut position_values: HashMap<String, f64> = HashMap::new();
        for (sym, &w) in &config.current_weights {
            position_values.insert(sym.clone(), w * total_value);
        }

        // Apply each order.
        for order in orders {
            let entry = position_values.entry(order.symbol.clone()).or_insert(0.0);
            match order.side {
                OrderSide::Buy => *entry += order.dollar_value,
                OrderSide::Sell => *entry -= order.dollar_value,
            }
            // Clamp to zero (can't have negative position value in a long-only book).
            if *entry < 0.0 {
                *entry = 0.0;
            }
        }

        // Account for transaction costs.
        let total_cost = Self::estimate_cost(orders, config);
        let post_value = total_value - total_cost;
        let post_value = post_value.max(1.0);

        // Convert back to weights.
        let mut weights: HashMap<String, f64> = HashMap::new();
        for (sym, &pos_val) in &position_values {
            weights.insert(sym.clone(), pos_val / post_value);
        }

        weights
    }

    /// Check whether any weight has drifted more than `threshold` from its target.
    ///
    /// Returns `true` if rebalancing is needed, `false` otherwise.
    pub fn drift_check(
        current: &HashMap<String, f64>,
        target: &HashMap<String, f64>,
        threshold: f64,
    ) -> bool {
        // Check all target symbols.
        for (sym, &target_w) in target {
            let current_w = current.get(sym).copied().unwrap_or(0.0);
            if (current_w - target_w).abs() > threshold {
                return true;
            }
        }
        // Also check symbols in current but not in target (should drift to zero).
        for (sym, &current_w) in current {
            if !target.contains_key(sym) && current_w.abs() > threshold {
                return true;
            }
        }
        false
    }

    /// Compute the total one-way turnover for a set of orders relative to portfolio value.
    pub fn compute_turnover(orders: &[RebalanceOrder], total_value: f64) -> f64 {
        if total_value <= 0.0 {
            return 0.0;
        }
        let total_traded: f64 = orders.iter().map(|o| o.dollar_value).sum();
        total_traded / total_value
    }

    /// Compute signed weight deltas (target - current) for all symbols.
    pub fn weight_deltas(config: &RebalanceConfig) -> HashMap<String, f64> {
        let mut all_symbols: std::collections::HashSet<String> = std::collections::HashSet::new();
        for k in config.target_weights.keys() {
            all_symbols.insert(k.clone());
        }
        for k in config.current_weights.keys() {
            all_symbols.insert(k.clone());
        }

        let mut deltas = HashMap::new();
        for sym in all_symbols {
            let target_w = config.target_weights.get(&sym).copied().unwrap_or(0.0);
            let current_w = config.current_weights.get(&sym).copied().unwrap_or(0.0);
            deltas.insert(sym, target_w - current_w);
        }
        deltas
    }

    /// Return the maximum absolute drift across all symbols.
    pub fn max_drift(current: &HashMap<String, f64>, target: &HashMap<String, f64>) -> f64 {
        let mut max_d = 0.0_f64;
        let mut all_symbols: std::collections::HashSet<&String> = std::collections::HashSet::new();
        for k in current.keys() {
            all_symbols.insert(k);
        }
        for k in target.keys() {
            all_symbols.insert(k);
        }
        for sym in all_symbols {
            let c = current.get(sym).copied().unwrap_or(0.0);
            let t = target.get(sym).copied().unwrap_or(0.0);
            let d = (c - t).abs();
            if d > max_d {
                max_d = d;
            }
        }
        max_d
    }

    /// Compute the weighted average transaction cost in bps across all orders.
    pub fn weighted_avg_cost_bps(orders: &[RebalanceOrder]) -> f64 {
        let total_value: f64 = orders.iter().map(|o| o.dollar_value).sum();
        if total_value <= 0.0 {
            return 0.0;
        }
        orders
            .iter()
            .map(|o| o.estimated_cost_bps * o.dollar_value / total_value)
            .sum()
    }

    /// Split orders into buys and sells.
    pub fn split_orders(
        orders: &[RebalanceOrder],
    ) -> (Vec<&RebalanceOrder>, Vec<&RebalanceOrder>) {
        let buys: Vec<&RebalanceOrder> =
            orders.iter().filter(|o| o.side == OrderSide::Buy).collect();
        let sells: Vec<&RebalanceOrder> =
            orders.iter().filter(|o| o.side == OrderSide::Sell).collect();
        (buys, sells)
    }

    /// Total dollar value of buy orders.
    pub fn total_buy_value(orders: &[RebalanceOrder]) -> f64 {
        orders
            .iter()
            .filter(|o| o.side == OrderSide::Buy)
            .map(|o| o.dollar_value)
            .sum()
    }

    /// Total dollar value of sell orders.
    pub fn total_sell_value(orders: &[RebalanceOrder]) -> f64 {
        orders
            .iter()
            .filter(|o| o.side == OrderSide::Sell)
            .map(|o| o.dollar_value)
            .sum()
    }

    /// Check whether executing these orders would exceed the cash constraint.
    /// Returns true if there is enough cash (sells + existing cash >= buys).
    pub fn cash_feasibility_check(orders: &[RebalanceOrder], available_cash: f64) -> bool {
        let total_sells = Self::total_sell_value(orders);
        let total_buys = Self::total_buy_value(orders);
        (total_sells + available_cash) >= total_buys - 1e-6
    }

    /// Summarize a set of orders into a human-readable string.
    pub fn summarize(orders: &[RebalanceOrder], config: &RebalanceConfig) -> String {
        let total_value = Self::portfolio_value(config);
        let turnover = Self::compute_turnover(orders, total_value);
        let cost_usd = Self::estimate_cost(orders, config);
        let (buys, sells) = Self::split_orders(orders);
        format!(
            "Orders: {} total ({} buys, {} sells) | Turnover: {:.2}% | Est. cost: ${:.2}",
            orders.len(),
            buys.len(),
            sells.len(),
            turnover * 100.0,
            cost_usd
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_config() -> RebalanceConfig {
        let mut target = HashMap::new();
        target.insert("AAPL".to_string(), 0.40);
        target.insert("MSFT".to_string(), 0.40);
        target.insert("GOOG".to_string(), 0.20);

        let mut current = HashMap::new();
        current.insert("AAPL".to_string(), 0.33);
        current.insert("MSFT".to_string(), 0.33);
        current.insert("GOOG".to_string(), 0.34);

        let mut prices = HashMap::new();
        prices.insert("AAPL".to_string(), 180.0);
        prices.insert("MSFT".to_string(), 370.0);
        prices.insert("GOOG".to_string(), 140.0);

        RebalanceConfig {
            target_weights: target,
            current_weights: current,
            current_prices: prices,
            cash: 1000.0,
            max_turnover: 0.50,
            min_trade_size_usd: 50.0,
            transaction_cost_bps: 5.0,
        }
    }

    #[test]
    fn test_compute_orders_basic() {
        let config = make_config();
        let orders = Rebalancer::compute_orders(&config);
        // Should generate some orders since weights are misaligned.
        assert!(!orders.is_empty());
    }

    #[test]
    fn test_drift_check_above_threshold() {
        let config = make_config();
        let triggered =
            Rebalancer::drift_check(&config.current_weights, &config.target_weights, 0.01);
        assert!(triggered, "Drift should be detected with 1% threshold");
    }

    #[test]
    fn test_drift_check_below_threshold() {
        let config = make_config();
        // With a very wide threshold, no drift should be detected.
        let triggered =
            Rebalancer::drift_check(&config.current_weights, &config.target_weights, 0.50);
        assert!(!triggered, "No drift with 50% threshold");
    }

    #[test]
    fn test_simulate_post_weights_sum() {
        let config = make_config();
        let orders = Rebalancer::compute_orders(&config);
        let post_weights = Rebalancer::simulate_post_rebalance_weights(&orders, &config);
        let total: f64 = post_weights.values().sum();
        // After rebalancing, weights should sum to approximately 1.0 (minus cost drag).
        assert!(total > 0.0 && total <= 1.01, "Post-rebalance weights sum {:.4}", total);
    }

    #[test]
    fn test_no_orders_when_weights_match() {
        let mut config = make_config();
        config.current_weights = config.target_weights.clone();
        let orders = Rebalancer::compute_orders(&config);
        assert!(
            orders.is_empty(),
            "No orders expected when weights already match"
        );
    }
}
