"""
Hypothesis Exchange: marketplace for validated alpha templates.

Instead of selling signals (perishable), sell the LOGIC (durable IP):
  - Validated hypothesis templates with full backtest proof
  - Dream-tested fragility certificates
  - Debate transcripts showing multi-agent validation
  - Provenance traces from physics concept to trade logic

Revenue model:
  - Per-hypothesis purchase (one-time fee)
  - Subscription to new hypothesis stream (monthly)
  - Revenue share on profits generated by purchased hypotheses
  - Premium: custom hypothesis synthesis for client's specific universe

Defensibility: the physics-to-trade pipeline is the moat. Competitors
can replicate individual signals but not the systematic discovery process.
"""

from __future__ import annotations
import json
import time
import hashlib
from dataclasses import dataclass, field
from typing import Dict, List, Optional


# ---------------------------------------------------------------------------
# Marketplace Listings
# ---------------------------------------------------------------------------

@dataclass
class HypothesisListing:
    """A hypothesis listed for sale on the marketplace."""
    listing_id: str
    name: str
    category: str                 # physics_alpha / microstructure / macro / cross_asset
    physics_concept: str
    description: str

    # Validation proof
    backtest_sharpe: float
    backtest_sortino: float
    backtest_max_dd: float
    backtest_period: str          # "2021-01 to 2026-03"
    oos_sharpe: float             # out-of-sample
    deflated_sharpe: float        # adjusted for multiple testing
    n_backtest_trades: int

    # Dream testing
    dream_survival_rate: float    # fraction of dream scenarios survived
    dream_fragility_index: float
    worst_dream_scenario: str

    # Debate validation
    debate_consensus: float       # 0-1 consensus from multi-agent debate
    n_debate_agents: int
    risk_manager_approved: bool

    # Provenance
    provenance_depth: int         # layers in the decision chain
    ehs_generation: int           # which EHS cycle discovered this

    # Commercial
    price_usd: float
    subscription_monthly_usd: float = 0.0
    revenue_share_pct: float = 0.0
    times_purchased: int = 0
    avg_buyer_sharpe: float = 0.0  # how buyers have performed

    # Metadata
    created_at: float = 0.0
    last_validated: float = 0.0
    status: str = "active"        # active / deprecated / sold_out

    # The actual template (the IP being sold)
    template_code: str = ""       # Python code for the signal
    entry_rules: List[str] = field(default_factory=list)
    exit_rules: List[str] = field(default_factory=list)
    regime_applicability: List[str] = field(default_factory=list)
    risk_parameters: Dict = field(default_factory=dict)


@dataclass
class Purchase:
    """Record of a hypothesis purchase."""
    purchase_id: str
    listing_id: str
    buyer_id: str
    price_paid: float
    purchased_at: float
    license_type: str             # "perpetual" / "subscription" / "revenue_share"
    buyer_reported_sharpe: float = 0.0
    buyer_reported_pnl: float = 0.0


# ---------------------------------------------------------------------------
# Pricing Engine
# ---------------------------------------------------------------------------

class PricingEngine:
    """Dynamic pricing based on validation quality and market demand."""

    BASE_PRICES = {
        "physics_alpha": 2999,
        "microstructure": 1999,
        "macro": 1499,
        "cross_asset": 2499,
    }

    @staticmethod
    def compute_price(listing: HypothesisListing) -> float:
        """Compute the listing price based on quality metrics."""
        base = PricingEngine.BASE_PRICES.get(listing.category, 1999)

        # Quality multipliers
        sharpe_mult = min(3.0, max(0.5, listing.oos_sharpe / 0.5))
        dream_mult = max(0.3, listing.dream_survival_rate * 1.5)
        debate_mult = max(0.5, listing.debate_consensus * 1.3)
        demand_mult = 1.0 + min(listing.times_purchased * 0.05, 1.0)

        price = base * sharpe_mult * dream_mult * debate_mult * demand_mult

        # Cap at reasonable range
        return round(max(499, min(49999, price)), -1)  # round to nearest 10

    @staticmethod
    def compute_subscription_price(listing: HypothesisListing) -> float:
        """Monthly subscription for ongoing updates to the hypothesis."""
        return round(PricingEngine.compute_price(listing) * 0.15, -1)

    @staticmethod
    def compute_revenue_share(listing: HypothesisListing) -> float:
        """Revenue share percentage (lower upfront cost, share profits)."""
        base_share = 5.0  # 5% base
        # Higher quality = lower share needed (buyer gets better deal)
        quality = (listing.oos_sharpe + listing.dream_survival_rate) / 2
        adjusted = max(2.0, base_share - quality * 2)
        return round(adjusted, 1)


# ---------------------------------------------------------------------------
# Marketplace
# ---------------------------------------------------------------------------

class HypothesisMarketplace:
    """
    The Hypothesis Exchange: buy and sell validated alpha templates.

    For sellers (us): list hypotheses that passed EHS -> Debate -> Dream validation
    For buyers: browse, purchase, and deploy hypothesis templates
    """

    def __init__(self):
        self._listings: Dict[str, HypothesisListing] = {}
        self._purchases: List[Purchase] = []
        self._counter = 0

    def _next_id(self, prefix: str) -> str:
        self._counter += 1
        return f"{prefix}_{self._counter:06d}"

    def list_hypothesis(
        self,
        name: str,
        category: str,
        physics_concept: str,
        description: str,
        backtest_sharpe: float,
        backtest_sortino: float,
        backtest_max_dd: float,
        oos_sharpe: float,
        deflated_sharpe: float,
        dream_survival_rate: float,
        dream_fragility: float,
        debate_consensus: float,
        template_code: str = "",
        entry_rules: List[str] = None,
        exit_rules: List[str] = None,
        regime_applicability: List[str] = None,
    ) -> HypothesisListing:
        """List a new hypothesis for sale."""
        listing = HypothesisListing(
            listing_id=self._next_id("listing"),
            name=name,
            category=category,
            physics_concept=physics_concept,
            description=description,
            backtest_sharpe=backtest_sharpe,
            backtest_sortino=backtest_sortino,
            backtest_max_dd=backtest_max_dd,
            backtest_period="2021-01 to 2026-03",
            oos_sharpe=oos_sharpe,
            deflated_sharpe=deflated_sharpe,
            n_backtest_trades=500,
            dream_survival_rate=dream_survival_rate,
            dream_fragility_index=dream_fragility,
            worst_dream_scenario="gravity_intensification",
            debate_consensus=debate_consensus,
            n_debate_agents=12,
            risk_manager_approved=debate_consensus > 0.6,
            provenance_depth=7,
            ehs_generation=1,
            template_code=template_code,
            entry_rules=entry_rules or [],
            exit_rules=exit_rules or [],
            regime_applicability=regime_applicability or [],
            created_at=time.time(),
            last_validated=time.time(),
            price_usd=0.0,
        )

        # Dynamic pricing
        listing.price_usd = PricingEngine.compute_price(listing)
        listing.subscription_monthly_usd = PricingEngine.compute_subscription_price(listing)
        listing.revenue_share_pct = PricingEngine.compute_revenue_share(listing)

        self._listings[listing.listing_id] = listing
        return listing

    def purchase(self, listing_id: str, buyer_id: str,
                  license_type: str = "perpetual") -> Optional[Purchase]:
        """Process a purchase."""
        listing = self._listings.get(listing_id)
        if not listing or listing.status != "active":
            return None

        if license_type == "perpetual":
            price = listing.price_usd
        elif license_type == "subscription":
            price = listing.subscription_monthly_usd
        elif license_type == "revenue_share":
            price = listing.price_usd * 0.3  # 30% upfront + revenue share
        else:
            price = listing.price_usd

        purchase = Purchase(
            purchase_id=self._next_id("purchase"),
            listing_id=listing_id,
            buyer_id=buyer_id,
            price_paid=price,
            purchased_at=time.time(),
            license_type=license_type,
        )

        self._purchases.append(purchase)
        listing.times_purchased += 1

        # Re-price based on demand
        listing.price_usd = PricingEngine.compute_price(listing)

        return purchase

    def browse(self, category: Optional[str] = None,
                min_sharpe: float = 0.0,
                max_fragility: float = 1.0,
                sort_by: str = "oos_sharpe") -> List[dict]:
        """Browse available hypotheses."""
        results = []
        for listing in self._listings.values():
            if listing.status != "active":
                continue
            if category and listing.category != category:
                continue
            if listing.oos_sharpe < min_sharpe:
                continue
            if listing.dream_fragility_index > max_fragility:
                continue

            results.append({
                "listing_id": listing.listing_id,
                "name": listing.name,
                "category": listing.category,
                "physics_concept": listing.physics_concept,
                "oos_sharpe": listing.oos_sharpe,
                "dream_survival": listing.dream_survival_rate,
                "debate_consensus": listing.debate_consensus,
                "price_usd": listing.price_usd,
                "subscription_monthly": listing.subscription_monthly_usd,
                "revenue_share_pct": listing.revenue_share_pct,
                "times_purchased": listing.times_purchased,
                "regime_applicability": listing.regime_applicability,
            })

        sort_keys = {
            "oos_sharpe": lambda x: x["oos_sharpe"],
            "price": lambda x: x["price_usd"],
            "popularity": lambda x: x["times_purchased"],
            "dream_survival": lambda x: x["dream_survival"],
        }
        results.sort(key=sort_keys.get(sort_by, sort_keys["oos_sharpe"]), reverse=True)
        return results

    def revenue_report(self) -> dict:
        """Revenue analytics."""
        total_revenue = sum(p.price_paid for p in self._purchases)
        active_subs = sum(1 for p in self._purchases if p.license_type == "subscription")
        rev_shares = sum(1 for p in self._purchases if p.license_type == "revenue_share")

        by_category = defaultdict(float)
        for p in self._purchases:
            listing = self._listings.get(p.listing_id)
            if listing:
                by_category[listing.category] += p.price_paid

        return {
            "total_revenue": total_revenue,
            "total_purchases": len(self._purchases),
            "active_subscriptions": active_subs,
            "revenue_share_deals": rev_shares,
            "revenue_by_category": dict(by_category),
            "active_listings": sum(1 for l in self._listings.values() if l.status == "active"),
            "avg_listing_price": float(
                sum(l.price_usd for l in self._listings.values()) / max(len(self._listings), 1)
            ),
            "most_popular": max(self._listings.values(), key=lambda l: l.times_purchased).name
            if self._listings else None,
        }
