"""
template_engine.py — Hand-Rolled Template Engine
=================================================
A lightweight Jinja2-style template system that uses only the Python
standard library.  Supports variable substitution, for-loops,
if/else conditionals, and include directives.

Template syntax
---------------
Variables:
    {{ variable }}
    {{ dict.key }}
    {{ list.0 }}

For loops:
    {% for item in items %}
    ... {{ item }} ...
    {% endfor %}

    {% for key, value in dict.items() %}
    ... {{ key }}: {{ value }} ...
    {% endfor %}

Conditionals:
    {% if condition %}
    ...
    {% elif other %}
    ...
    {% else %}
    ...
    {% endif %}

Filters:
    {{ value | upper }}
    {{ value | lower }}
    {{ value | title }}
    {{ value | strip }}
    {{ value | default("fallback") }}
    {{ value | round(2) }}
    {{ value | truncate(80) }}
    {{ value | join(", ") }}
    {{ value | len }}

Comments:
    {# This is a comment #}

Usage
-----
    engine = TemplateEngine()
    engine.register("greeting", "Hello, {{ name }}!")
    result = engine.render("greeting", {"name": "World"})
    # -> "Hello, World!"

    # Or use built-in templates:
    result = engine.render("weekly_report", context_dict)
"""

from __future__ import annotations

import re
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

# ---------------------------------------------------------------------------
# Built-in templates
# ---------------------------------------------------------------------------

BUILTIN_TEMPLATES: Dict[str, str] = {

    # -----------------------------------------------------------------------
    "weekly_report": """\
# Weekly Research Report — {{ week_label }}

Generated: {{ generated_at }}

---

## Executive Summary

{{ executive_summary }}

---

## Top Performing Genome

{% if top_genome %}
**Genome ID:** `{{ top_genome.genome_id }}`
**Fitness:** {{ top_genome.fitness | round(4) }}
**Generation:** {{ top_genome.generation }}
**Description:** {{ top_genome.description | default("No description.") }}
**Strategy:** {{ top_genome.strategy | default("N/A") }}
{% else %}
*No genome data available this week.*
{% endif %}

---

## Best Counterfactual Discovery

{% if best_counterfactual %}
**ID:** `{{ best_counterfactual.id }}`
**Improvement Found:** {{ best_counterfactual.improvement_pct | round(2) }}%
**Modified Parameter:** {{ best_counterfactual.parameter }}
**Original Value:** {{ best_counterfactual.original_value }}
**Counterfactual Value:** {{ best_counterfactual.cf_value }}
**Summary:** {{ best_counterfactual.summary | default("See details in DB.") }}
{% else %}
*No counterfactual discoveries this week.*
{% endif %}

---

## Shadow Runner Results

{% if shadow_results %}
{% for shadow in shadow_results %}
- **{{ shadow.shadow_id }}**: Live PnL={{ shadow.live_pnl | round(4) }}, Shadow PnL={{ shadow.shadow_pnl | round(4) }}, Delta={{ shadow.delta | round(4) }}{% if shadow.beating %} ⚑ SHADOW BEATING LIVE{% endif %}

{% endfor %}
{% else %}
*No shadow runner data available this week.*
{% endif %}

---

## Top 5 New Hypotheses

{% if hypotheses %}
{% for h in hypotheses %}
{{ loop.index }}. **[{{ h.mapped_component | upper }}]** {{ h.hypothesis_text }}
   - Confidence: {{ h.confidence | round(3) }}
   - Status: {{ h.status }}
   - Created: {{ h.created_at }}

{% endfor %}
{% else %}
*No new hypotheses generated this week.*
{% endif %}

---

## Academic Papers Mined

{% if papers %}
{% for p in papers %}
- **[{{ p.source | upper }}]** {{ p.title | truncate(80) }}
  - Score: {{ p.relevance_score | round(3) }}  |  Mined: {{ p.mined_at }}
  - URL: {{ p.url | default("N/A") }}

{% endfor %}
{% else %}
*No academic papers mined this week.*
{% endif %}

---

## Serendipity Ideas Worth Trying

{% if serendipity_ideas %}
{% for idea in serendipity_ideas %}
{{ loop.index }}. **[{{ idea.technique | upper }}]** {{ idea.idea_text | truncate(100) }}
   - Complexity: {{ idea.complexity }}  |  Score: {{ idea.score | round(3) }}

{% endfor %}
{% else %}
*No serendipity ideas generated this week.*
{% endif %}

---

## Causal Discoveries

{% if causal_links %}
{% for link in causal_links %}
- **{{ link.cause }}** → **{{ link.effect }}** (p={{ link.pvalue | round(4) }}, lag={{ link.lag }})

{% endfor %}
{% else %}
*No new Granger causality links discovered this week.*
{% endif %}

---

*Report generated by IAE Narrative Intelligence v{{ version | default("0.1.0") }}*
""",

    # -----------------------------------------------------------------------
    "idea_card": """\
# Idea Card — Hypothesis #{{ hypothesis_id }}

**Created:** {{ created_at }}
**Status:** {{ status | upper }}
**Confidence:** {{ confidence | round(3) }}

---

## Hypothesis

{{ hypothesis_text }}

---

## Strategy Component

**Component:** `{{ mapped_component }}`

## Suggested Parameters

{% if param_suggestions %}
{% for key, value in param_suggestions.items() %}
- `{{ key }}`: {{ value }}
{% endfor %}
{% else %}
*No specific parameter suggestions.*
{% endif %}

---

## Source Paper

{% if paper_title %}
**Title:** {{ paper_title }}
**Source:** {{ paper_source | upper }}
**Relevance Score:** {{ paper_score | default("N/A") | round(3) }}
{% else %}
*No source paper linked.*
{% endif %}

---

## Experiment Plan

{{ experiment_plan | default("Run parameter sweep on identified component. Measure Sharpe improvement over 3-month OOS window.") }}

---

*Generated by IAE Narrative Intelligence*
""",

    # -----------------------------------------------------------------------
    "genome_bio": """\
# Genome Biography — `{{ genome_id }}`

**Born:** Generation {{ birth_generation }}
**Current Generation:** {{ current_generation }}
**Status:** {{ status | upper }}

---

## Lineage

{% if parent_id %}
**Parent:** `{{ parent_id }}`
{% if parent_fitness %}(Parent fitness: {{ parent_fitness | round(4) }}){% endif %}

{% else %}
**Origin:** Primordial (no parent — random initialisation or seed genome)
{% endif %}

{% if mutations %}
**Mutations Applied:**
{% for m in mutations %}
- {{ m }}
{% endfor %}
{% endif %}

---

## Performance Arc

| Generation | Fitness | Sharpe | MaxDD  | Note            |
|-----------|---------|--------|--------|-----------------|
{% for row in performance_arc %}
| {{ row.generation }} | {{ row.fitness | round(4) }} | {{ row.sharpe | default("N/A") }} | {{ row.maxdd | default("N/A") }} | {{ row.note | default("") }} |
{% endfor %}

---

## Strategy Parameters

{% if params %}
{% for key, value in params.items() %}
- **{{ key }}**: {{ value }}
{% endfor %}
{% else %}
*Parameter data not available.*
{% endif %}

---

## Notable Events

{% if events %}
{% for event in events %}
- **Gen {{ event.generation }}:** {{ event.description }}
{% endfor %}
{% else %}
*No notable events recorded.*
{% endif %}

---

*Biography generated by IAE Narrative Intelligence*
""",

    # -----------------------------------------------------------------------
    "regime_summary": """\
# Regime Summary — {{ regime_name | upper }}

**Observed Period:** {{ period_start }} → {{ period_end }}
**Duration:** {{ duration_days }} days
**Confidence:** {{ confidence | round(2) }}

---

## Regime Characteristics

{{ regime_description }}

---

## What's Working in This Regime

{% if working_strategies %}
{% for s in working_strategies %}
- **{{ s.name }}**: Sharpe={{ s.sharpe | round(3) }}, WinRate={{ s.win_rate | round(1) }}%
{% endfor %}
{% else %}
*No strategy-specific data for this regime.*
{% endif %}

---

## What's Not Working

{% if failing_strategies %}
{% for s in failing_strategies %}
- **{{ s.name }}**: Sharpe={{ s.sharpe | round(3) }} (below threshold)
{% endfor %}
{% else %}
*No underperforming strategies identified.*
{% endif %}

---

## Recommended Actions

{% if recommendations %}
{% for r in recommendations %}
{{ loop.index }}. {{ r }}
{% endfor %}
{% else %}
*No specific recommendations generated.*
{% endif %}

---

*Regime analysis by IAE Narrative Intelligence*
""",

    # -----------------------------------------------------------------------
    "alert_message": """\
[ALERT] **IAE ALERT** -- {{ alert_type | upper }}
Severity: {{ severity | upper }}
Time: {{ created_at }}

{{ message }}

{% if data %}
**Details:**
{% for key, value in data.items() %}
  {{ key }}: {{ value }}
{% endfor %}
{% endif %}

*Acknowledge with: idea-api alert ack {{ alert_id }}*
""",
}


# ---------------------------------------------------------------------------
# TemplateEngine
# ---------------------------------------------------------------------------

class TemplateEngine:
    """
    A lightweight, Jinja2-inspired template engine using only stdlib.

    Supported syntax
    ----------------
    - ``{{ var }}`` — variable interpolation with optional filter chain
    - ``{% for x in xs %}`` / ``{% endfor %}``
    - ``{% for k, v in d.items() %}`` / ``{% endfor %}``
    - ``{% if cond %}`` / ``{% elif cond %}`` / ``{% else %}`` / ``{% endif %}``
    - ``{{ loop.index }}`` inside for loops (1-based)
    - ``{# comment #}`` — stripped during rendering
    - Filters: upper, lower, title, strip, default, round, truncate,
               join, len, items

    Parameters
    ----------
    auto_escape : bool
        If True, escape < > & in variable output (HTML mode).
    """

    def __init__(self, auto_escape: bool = False) -> None:
        self._templates: Dict[str, str] = dict(BUILTIN_TEMPLATES)
        self.auto_escape = auto_escape

    # ------------------------------------------------------------------
    # Template management
    # ------------------------------------------------------------------

    def register(self, name: str, template: str) -> None:
        """Register a named template string."""
        self._templates[name] = template

    def has(self, name: str) -> bool:
        """Return True if template *name* is registered."""
        return name in self._templates

    def list_templates(self) -> List[str]:
        """Return sorted list of registered template names."""
        return sorted(self._templates.keys())

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def render(self, template_name: str, context: dict) -> str:
        """
        Render a named template with *context*.

        Parameters
        ----------
        template_name : str
        context : dict

        Returns
        -------
        str
            Rendered template text.

        Raises
        ------
        KeyError
            If template_name is not registered.
        """
        if template_name not in self._templates:
            raise KeyError(
                f"Template {template_name!r} not found. "
                f"Available: {self.list_templates()}"
            )
        source = self._templates[template_name]
        return self.render_string(source, context)

    def render_string(self, source: str, context: dict) -> str:
        """
        Render a template string directly (no registration required).

        Parameters
        ----------
        source : str
        context : dict

        Returns
        -------
        str
        """
        # Step 1: strip comments
        source = re.sub(r"\{#.*?#\}", "", source, flags=re.DOTALL)
        # Step 2: process block tags (for / if)
        result = self._process_blocks(source, context)
        # Step 3: interpolate remaining {{ }} expressions
        result = self._interpolate(result, context)
        return result

    # ------------------------------------------------------------------
    # Block processing
    # ------------------------------------------------------------------

    def _process_blocks(self, source: str, context: dict) -> str:
        """
        Recursively process {% for %} and {% if %} block tags.

        Uses a token-based approach: tokenise into text segments and
        block tags, then evaluate in order.
        """
        tokens = self._tokenise(source)
        output, _ = self._eval_tokens(tokens, 0, context)
        return output

    def _tokenise(self, source: str) -> List[Tuple[str, str]]:
        """
        Split source into a flat list of (type, content) tokens.

        Types: 'text', 'var', 'tag'
        """
        tokens: List[Tuple[str, str]] = []
        pattern = re.compile(
            r"(\{\{.*?\}\}|\{%.*?%\})",
            re.DOTALL,
        )
        pos = 0
        for m in pattern.finditer(source):
            if m.start() > pos:
                tokens.append(("text", source[pos:m.start()]))
            raw = m.group(1).strip()
            if raw.startswith("{{"):
                inner = raw[2:-2].strip()
                tokens.append(("var", inner))
            else:
                inner = raw[2:-2].strip()
                tokens.append(("tag", inner))
            pos = m.end()
        if pos < len(source):
            tokens.append(("text", source[pos:]))
        return tokens

    def _eval_tokens(
        self,
        tokens: List[Tuple[str, str]],
        pos: int,
        context: dict,
    ) -> Tuple[str, int]:
        """
        Evaluate tokens starting at *pos*, returning (rendered_text, new_pos).

        Stops when it encounters an {% endfor %}, {% endif %},
        {% else %}, or {% elif %} tag at the current nesting level.
        """
        output: List[str] = []
        n = len(tokens)
        while pos < n:
            typ, content = tokens[pos]
            if typ == "text":
                output.append(content)
                pos += 1
            elif typ == "var":
                output.append(self._eval_var(content, context))
                pos += 1
            elif typ == "tag":
                tag_stripped = content.strip()
                if tag_stripped in ("endfor", "endif"):
                    return "".join(output), pos + 1
                if tag_stripped in ("else",) or tag_stripped.startswith("elif "):
                    return "".join(output), pos  # caller handles
                if tag_stripped.startswith("for "):
                    rendered, pos = self._eval_for(tokens, pos, context)
                    output.append(rendered)
                elif tag_stripped.startswith("if "):
                    rendered, pos = self._eval_if(tokens, pos, context)
                    output.append(rendered)
                else:
                    pos += 1  # unknown tag — skip
            else:
                pos += 1
        return "".join(output), pos

    def _eval_for(
        self,
        tokens: List[Tuple[str, str]],
        pos: int,
        context: dict,
    ) -> Tuple[str, int]:
        """Process a {% for ... %} block."""
        _, tag_content = tokens[pos]
        pos += 1

        # Parse: for VAR in ITERABLE  or  for K, V in DICT.items()
        m = re.match(
            r"for\s+(\w+(?:\s*,\s*\w+)?)\s+in\s+(.+)$",
            tag_content.strip(),
        )
        if not m:
            return "", pos

        var_part = m.group(1)
        iter_expr = m.group(2).strip()

        # Collect body tokens until endfor
        body_start = pos
        depth = 1
        end_pos = pos
        while end_pos < len(tokens):
            t, c = tokens[end_pos]
            if t == "tag":
                c = c.strip()
                if c.startswith("for "):
                    depth += 1
                elif c == "endfor":
                    depth -= 1
                    if depth == 0:
                        break
            end_pos += 1
        body_tokens = tokens[body_start:end_pos]
        pos = end_pos + 1  # skip 'endfor'

        # Resolve iterable
        iterable = self._resolve(iter_expr, context)
        if iterable is None:
            return "", pos

        # Determine if key-value iteration (for k, v in d.items())
        vars_ = [v.strip() for v in var_part.split(",")]
        output_parts: List[str] = []

        if isinstance(iterable, dict):
            items: Any = iterable.items()
        else:
            items = enumerate(iterable) if len(vars_) == 2 and "," in var_part else iterable

        loop_index = 0
        for item in items:
            loop_index += 1
            local_ctx = dict(context)
            local_ctx["loop"] = {"index": loop_index, "index0": loop_index - 1}
            if len(vars_) == 2:
                if isinstance(item, (tuple, list)) and len(item) >= 2:
                    local_ctx[vars_[0]] = item[0]
                    local_ctx[vars_[1]] = item[1]
                else:
                    local_ctx[vars_[0]] = loop_index - 1
                    local_ctx[vars_[1]] = item
            else:
                local_ctx[vars_[0]] = item

            rendered, _ = self._eval_tokens(body_tokens, 0, local_ctx)
            output_parts.append(rendered)

        return "".join(output_parts), pos

    def _eval_if(
        self,
        tokens: List[Tuple[str, str]],
        pos: int,
        context: dict,
    ) -> Tuple[str, int]:
        """Process {% if %} / {% elif %} / {% else %} / {% endif %} blocks."""
        _, tag_content = tokens[pos]
        pos += 1

        def collect_branch(start: int) -> Tuple[List[Tuple[str, str]], str, int]:
            """Collect tokens until elif/else/endif; return (body, next_tag, pos)."""
            depth  = 1
            branch_tokens: List[Tuple[str, str]] = []
            p      = start
            while p < len(tokens):
                t, c = tokens[p]
                if t == "tag":
                    c_strip = c.strip()
                    if c_strip.startswith("if "):
                        depth += 1
                    elif c_strip == "endif":
                        depth -= 1
                        if depth == 0:
                            return branch_tokens, "endif", p + 1
                    elif depth == 1 and (
                        c_strip == "else" or c_strip.startswith("elif ")
                    ):
                        return branch_tokens, c_strip, p + 1
                branch_tokens.append(tokens[p])
                p += 1
            return branch_tokens, "endif", p

        # Parse the initial condition
        cond_text = re.sub(r"^if\s+", "", tag_content.strip())
        branches: List[Tuple[str, List[Tuple[str, str]]]] = [(cond_text, [])]

        # Collect first branch
        first_body, next_tag, pos = collect_branch(pos)
        branches[0] = (cond_text, first_body)

        # Collect elif/else branches
        while next_tag != "endif":
            if next_tag == "else":
                body, _, pos = collect_branch(pos)
                branches.append(("__else__", body))
                break
            elif next_tag.startswith("elif "):
                cond = re.sub(r"^elif\s+", "", next_tag)
                body, next_tag, pos = collect_branch(pos)
                branches.append((cond, body))

        # Evaluate branches in order
        for cond, body in branches:
            if cond == "__else__" or self._eval_condition(cond, context):
                rendered, _ = self._eval_tokens(body, 0, context)
                return rendered, pos

        return "", pos

    def _eval_condition(self, expr: str, context: dict) -> bool:
        """Evaluate a simple boolean condition string."""
        expr = expr.strip()

        # Handle 'not X'
        if expr.startswith("not "):
            return not self._eval_condition(expr[4:], context)

        # Handle 'X and Y'
        if " and " in expr:
            parts = expr.split(" and ", 1)
            return self._eval_condition(parts[0], context) and self._eval_condition(parts[1], context)

        # Handle 'X or Y'
        if " or " in expr:
            parts = expr.split(" or ", 1)
            return self._eval_condition(parts[0], context) or self._eval_condition(parts[1], context)

        val = self._resolve(expr, context)
        return bool(val)

    # ------------------------------------------------------------------
    # Variable resolution
    # ------------------------------------------------------------------

    def _eval_var(self, expr: str, context: dict) -> str:
        """Evaluate a {{ expr }} expression and return a string."""
        # Split filters: "value | filter1 | filter2(arg)"
        parts = [p.strip() for p in expr.split("|")]
        val   = self._resolve(parts[0], context)
        for filt in parts[1:]:
            val = self._apply_filter(val, filt)
        if val is None:
            return ""
        if self.auto_escape and isinstance(val, str):
            val = val.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return str(val)

    def _resolve(self, expr: str, context: dict) -> Any:
        """
        Resolve a dot-notation expression (e.g. "item.key", "list.0")
        against *context*.
        """
        expr = expr.strip()

        # String literal
        if (expr.startswith('"') and expr.endswith('"')) or \
           (expr.startswith("'") and expr.endswith("'")):
            return expr[1:-1]

        # Numeric literal
        try:
            return int(expr)
        except ValueError:
            pass
        try:
            return float(expr)
        except ValueError:
            pass

        # Boolean / None literals
        if expr == "True":   return True
        if expr == "False":  return False
        if expr == "None":   return None

        # .items() call
        if expr.endswith(".items()"):
            base = self._resolve(expr[:-8], context)
            return base.items() if isinstance(base, dict) else {}

        # Dot / bracket navigation
        parts = re.split(r"[.\[]", expr)
        val: Any = context
        for part in parts:
            part = part.rstrip("]").strip("'\"")
            if val is None:
                return None
            if isinstance(val, dict):
                val = val.get(part) if not part.isdigit() else val.get(int(part))
            elif isinstance(val, (list, tuple)):
                try:
                    val = val[int(part)]
                except (ValueError, IndexError):
                    return None
            elif hasattr(val, part):
                val = getattr(val, part)
                if callable(val):
                    val = val()
            else:
                return None
        return val

    # ------------------------------------------------------------------
    # Filters
    # ------------------------------------------------------------------

    def _apply_filter(self, value: Any, filter_expr: str) -> Any:
        """Apply a single filter expression to *value*."""
        # Parse filter name and optional argument
        m = re.match(r"(\w+)(?:\((.+)\))?", filter_expr.strip())
        if not m:
            return value

        name = m.group(1)
        raw_arg = m.group(2)

        FILTERS: Dict[str, Callable] = {
            "upper":    lambda v, _: str(v).upper(),
            "lower":    lambda v, _: str(v).lower(),
            "title":    lambda v, _: str(v).title(),
            "strip":    lambda v, _: str(v).strip(),
            "len":      lambda v, _: len(v) if v is not None else 0,
            "default":  lambda v, a: v if v else (a.strip('"\'') if a else ""),
            "round":    lambda v, a: round(float(v), int(a)) if a else round(float(v), 2),
            "truncate": lambda v, a: str(v)[:int(a)] + "…" if a and len(str(v)) > int(a) else str(v),
            "join":     lambda v, a: (a.strip('"\'') if a else ", ").join(str(i) for i in v) if v else "",
            "items":    lambda v, _: v.items() if isinstance(v, dict) else [],
        }

        fn = FILTERS.get(name)
        if fn:
            try:
                return fn(value, raw_arg)
            except Exception:
                return value
        return value

    # ------------------------------------------------------------------
    # Interpolation pass (for {{ }} remaining after block processing)
    # ------------------------------------------------------------------

    def _interpolate(self, text: str, context: dict) -> str:
        """Substitute remaining {{ ... }} expressions in *text*."""
        def replacer(m: re.Match) -> str:
            expr = m.group(1).strip()
            return self._eval_var(expr, context)

        return re.sub(r"\{\{(.*?)\}\}", replacer, text, flags=re.DOTALL)

    def __repr__(self) -> str:
        return f"TemplateEngine(templates={len(self._templates)})"


# ---------------------------------------------------------------------------
# CLI / demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    engine = TemplateEngine()
    print("Registered templates:", engine.list_templates())
    print()

    result = engine.render_string(
        "Hello, {{ name | upper }}! You have {{ items | len }} items.\n"
        "{% for item in items %}- {{ item }}\n{% endfor %}",
        {"name": "researcher", "items": ["momentum", "mean reversion", "vol breakout"]},
    )
    print(result)
