"""
Guardian: hard-limit risk controller that runs OUTSIDE the trading engine.

For institutional investors: a risk module that the autonomous system
CANNOT override. Runs in a separate process, polls account state directly,
and can halt trading + flatten positions independently.

The risk committee sets limits via a RiskManifest (YAML/JSON config).
The Guardian enforces them regardless of what the BH engine or RMEA decide.

This is the "airbag" that makes a $50M allocation possible.
"""

from __future__ import annotations
import json
import time
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class RiskManifest:
    """
    Hard limits set by the risk committee.
    These cannot be overridden by the autonomous system.
    """
    # Drawdown limits
    max_daily_drawdown_pct: float = 2.0       # halt if daily loss > 2%
    max_weekly_drawdown_pct: float = 5.0      # halt if weekly loss > 5%
    max_total_drawdown_pct: float = 15.0      # halt + flatten if total DD > 15%

    # Exposure limits
    max_gross_exposure_pct: float = 200.0     # max gross leverage 2x
    max_net_exposure_pct: float = 100.0       # max net exposure 1x
    max_single_position_pct: float = 10.0     # max single name
    max_sector_exposure_pct: float = 35.0     # max sector

    # Concentration
    max_hhi: float = 0.15                     # Herfindahl index limit
    min_positions: int = 5                    # must be diversified

    # VaR
    max_var_95_pct: float = 3.0              # max 1-day 95% VaR
    max_var_99_pct: float = 5.0              # max 1-day 99% VaR

    # Operational
    max_orders_per_hour: int = 200            # prevent runaway algo
    max_notional_per_order: float = 500000    # max single order size
    banned_symbols: List[str] = field(default_factory=list)

    # Meta
    last_updated: str = ""
    updated_by: str = ""
    version: int = 1


@dataclass
class GuardianAlert:
    """An alert generated by the Guardian."""
    alert_id: str
    severity: str                 # "warning" / "breach" / "critical" / "halt"
    rule_violated: str
    current_value: float
    limit_value: float
    message: str
    timestamp: float
    action_taken: str             # "none" / "order_rejected" / "trading_halted" / "positions_flattened"


class Guardian:
    """
    Hard-limit risk controller.

    Runs independently of the trading engine. Polls account state
    and enforces the RiskManifest. Can:
    - Reject individual orders that would breach limits
    - Halt trading when drawdown limits are hit
    - Flatten all positions in emergency

    The risk committee can update the manifest at any time.
    The trading engine has NO ability to modify or bypass the Guardian.
    """

    def __init__(self, manifest: RiskManifest = None,
                  manifest_path: str = "config/risk_manifest.json"):
        self.manifest = manifest or RiskManifest()
        self.manifest_path = manifest_path
        self._alerts: List[GuardianAlert] = []
        self._alert_counter = 0
        self._trading_halted = False
        self._halt_reason = ""
        self._orders_this_hour: List[float] = []
        self._daily_start_equity = 0.0
        self._weekly_start_equity = 0.0
        self._peak_equity = 0.0

    def load_manifest(self) -> None:
        """Load risk manifest from file (risk committee can update this)."""
        try:
            if os.path.exists(self.manifest_path):
                with open(self.manifest_path, "r") as f:
                    data = json.load(f)
                for key, value in data.items():
                    if hasattr(self.manifest, key):
                        setattr(self.manifest, key, value)
        except Exception:
            pass  # keep existing manifest on error

    def set_reference_equity(self, equity: float) -> None:
        """Set reference equity for drawdown calculations."""
        if self._daily_start_equity == 0:
            self._daily_start_equity = equity
        if self._weekly_start_equity == 0:
            self._weekly_start_equity = equity
        self._peak_equity = max(self._peak_equity, equity)

    def reset_daily(self, equity: float) -> None:
        """Call at start of each trading day."""
        self._daily_start_equity = equity
        self._orders_this_hour = []

    def reset_weekly(self, equity: float) -> None:
        """Call at start of each trading week."""
        self._weekly_start_equity = equity

    def _alert(self, severity: str, rule: str, current: float,
                limit: float, message: str, action: str) -> GuardianAlert:
        self._alert_counter += 1
        alert = GuardianAlert(
            alert_id=f"guardian_{self._alert_counter:06d}",
            severity=severity,
            rule_violated=rule,
            current_value=current,
            limit_value=limit,
            message=message,
            timestamp=time.time(),
            action_taken=action,
        )
        self._alerts.append(alert)
        return alert

    # ---------------------------------------------------------------------------
    # Pre-Trade Check: can this order proceed?
    # ---------------------------------------------------------------------------

    def check_order(
        self,
        symbol: str,
        side: str,
        quantity: float,
        price: float,
        current_equity: float,
        current_positions: Dict[str, float],  # symbol -> notional
    ) -> Dict:
        """
        Pre-trade risk check. Returns {"approved": bool, "reason": str}.
        This is the HARD GATE that the trading engine cannot bypass.
        """
        self.set_reference_equity(current_equity)

        # Reload manifest (risk committee may have changed it)
        self.load_manifest()

        m = self.manifest
        order_notional = quantity * price

        # 1. Trading halted?
        if self._trading_halted:
            return {"approved": False, "reason": f"Trading halted: {self._halt_reason}"}

        # 2. Banned symbol?
        if symbol in m.banned_symbols:
            self._alert("breach", "banned_symbol", 0, 0,
                        f"Order rejected: {symbol} is banned", "order_rejected")
            return {"approved": False, "reason": f"{symbol} is on the banned list"}

        # 3. Max order size
        if order_notional > m.max_notional_per_order:
            self._alert("breach", "max_notional_per_order", order_notional,
                        m.max_notional_per_order, f"Order too large: ${order_notional:,.0f}",
                        "order_rejected")
            return {"approved": False,
                     "reason": f"Order notional ${order_notional:,.0f} > limit ${m.max_notional_per_order:,.0f}"}

        # 4. Single position limit
        existing = current_positions.get(symbol, 0)
        new_position = existing + (order_notional if side == "buy" else -order_notional)
        position_pct = abs(new_position) / max(current_equity, 1e-10) * 100
        if position_pct > m.max_single_position_pct:
            self._alert("breach", "max_single_position", position_pct,
                        m.max_single_position_pct, f"{symbol} would be {position_pct:.1f}% of NAV",
                        "order_rejected")
            return {"approved": False,
                     "reason": f"Position would be {position_pct:.1f}% > limit {m.max_single_position_pct}%"}

        # 5. Gross exposure limit
        total_gross = sum(abs(v) for v in current_positions.values()) + order_notional
        gross_pct = total_gross / max(current_equity, 1e-10) * 100
        if gross_pct > m.max_gross_exposure_pct:
            self._alert("breach", "max_gross_exposure", gross_pct,
                        m.max_gross_exposure_pct, f"Gross exposure would be {gross_pct:.0f}%",
                        "order_rejected")
            return {"approved": False,
                     "reason": f"Gross exposure {gross_pct:.0f}% > limit {m.max_gross_exposure_pct}%"}

        # 6. Order rate limit
        now = time.time()
        self._orders_this_hour = [t for t in self._orders_this_hour if now - t < 3600]
        if len(self._orders_this_hour) >= m.max_orders_per_hour:
            self._alert("warning", "order_rate_limit", len(self._orders_this_hour),
                        m.max_orders_per_hour, "Order rate limit reached", "order_rejected")
            return {"approved": False, "reason": "Order rate limit reached"}

        self._orders_this_hour.append(now)
        return {"approved": True, "reason": ""}

    # ---------------------------------------------------------------------------
    # Continuous Monitoring
    # ---------------------------------------------------------------------------

    def check_portfolio(self, current_equity: float,
                          current_positions: Dict[str, float]) -> List[GuardianAlert]:
        """
        Continuous portfolio monitoring. Call on every bar.
        Returns list of new alerts (empty if healthy).
        """
        alerts = []
        self.set_reference_equity(current_equity)
        m = self.manifest

        # Daily drawdown
        if self._daily_start_equity > 0:
            daily_dd = (self._daily_start_equity - current_equity) / self._daily_start_equity * 100
            if daily_dd > m.max_daily_drawdown_pct:
                alert = self._alert("halt", "max_daily_drawdown", daily_dd,
                                     m.max_daily_drawdown_pct,
                                     f"Daily DD {daily_dd:.1f}% > limit {m.max_daily_drawdown_pct}%",
                                     "trading_halted")
                self._trading_halted = True
                self._halt_reason = f"Daily drawdown {daily_dd:.1f}%"
                alerts.append(alert)

        # Total drawdown from peak
        if self._peak_equity > 0:
            total_dd = (self._peak_equity - current_equity) / self._peak_equity * 100
            if total_dd > m.max_total_drawdown_pct:
                alert = self._alert("critical", "max_total_drawdown", total_dd,
                                     m.max_total_drawdown_pct,
                                     f"CRITICAL: Total DD {total_dd:.1f}% > limit {m.max_total_drawdown_pct}%",
                                     "positions_flattened")
                self._trading_halted = True
                self._halt_reason = f"Total drawdown {total_dd:.1f}% - FLATTEN ALL"
                alerts.append(alert)

        # Concentration (HHI)
        if current_positions and current_equity > 0:
            weights = [abs(v) / current_equity for v in current_positions.values()]
            hhi = sum(w ** 2 for w in weights)
            if hhi > m.max_hhi:
                alert = self._alert("warning", "max_hhi", hhi, m.max_hhi,
                                     f"Portfolio concentration HHI={hhi:.3f} > limit {m.max_hhi}",
                                     "none")
                alerts.append(alert)

        return alerts

    def is_halted(self) -> bool:
        return self._trading_halted

    def resume_trading(self, authorized_by: str) -> None:
        """Resume trading (risk committee action only)."""
        self._trading_halted = False
        self._halt_reason = ""
        self._alert("warning", "trading_resumed", 0, 0,
                     f"Trading resumed by {authorized_by}", "none")

    def get_status(self) -> Dict:
        """Get Guardian status for the risk dashboard."""
        return {
            "trading_halted": self._trading_halted,
            "halt_reason": self._halt_reason,
            "total_alerts": len(self._alerts),
            "critical_alerts": sum(1 for a in self._alerts if a.severity == "critical"),
            "manifest_version": self.manifest.version,
            "peak_equity": self._peak_equity,
            "daily_start_equity": self._daily_start_equity,
            "recent_alerts": [
                {"severity": a.severity, "rule": a.rule_violated, "message": a.message,
                 "action": a.action_taken}
                for a in self._alerts[-10:]
            ],
        }
